version: "3"

services:
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: localhost_dev
      MYSQL_PASSWORD: localhost_dev
      MYSQL_DATABASE: localhost_dev
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
