version: "3"

services:
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: localhost_dev
      MYSQL_PASSWORD: localhost_dev
      MYSQL_DATABASE: localhost_dev
    ports:
      - 3306:3306

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
