service:
  name: hasuki

app: hasuki
tenant: if1live

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2

plugins:
  - serverless-webpack

functions:
  simple:
    handler: index.handler
    events:
      - http:
        path: youtube/audio-url
        method: get
        cors: true

