service: hasuki

# app and org for use with dashboard.serverless.com
# org: if1live
# app: hasuki

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x

  region: ap-northeast-1
  stage: dev

  memorySize: 256
  architecture: arm64

  logRetentionInDays: 7
  versionFunctions: false

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE: ${self:provider.stage}

package:
  patterns:
    - "!**"
    - "!node_modules/**"
    - output/*.js
    - output/*.json

functions:
  http_handle:
    handler: output/index.handle_http
    events:
      - httpApi:
          method: "*"
          path: /{pathname+}

plugins:
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: npm run package
