service: hasuki

useDotenv: true

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs20.x

  region: ap-northeast-1
  stage: dev

  memorySize: 256
  architecture: arm64

  logRetentionInDays: 1
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    AWS_ACCOUNT_ID: ${aws:accountId}

    STAGE: ${self:provider.stage}
    NODE_ENV: production

    DATABASE_URL: ${env:DATABASE_URL}
    REDIS_URL: ${env:REDIS_URL}
    FRONTEND_URL: ${env:FRONTEND_URL}

package:
  individually: true
  patterns:
    - "!**"
    - "!node_modules/**"

functions:
  httpMain:
    handler: artifact/http_main.dispatch
    url: true
    package:
      patterns:
        - artifact/http_main.mjs*
        - views/**/*
        - static/**/*
    events:
      - httpApi: ANY /
      - httpApi: ANY /{pathname+}

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm artifact
